cmake_minimum_required(VERSION 3.10)
project(trange)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

file(GLOB_RECURSE SOURCES "src/*.cpp")
file(GLOB_RECURSE HEADERS "include/*.h")

add_executable(trange ${SOURCES})

target_include_directories(trange PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/include
)

target_link_libraries(trange PRIVATE pthread)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(trange PRIVATE -g -O0 -Wall -Wextra)
    message(STATUS "Debug")
else()
    target_compile_options(trange PRIVATE -O2)
    message(STATUS "Release")
endif()
